# Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele
n = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(n))
print('Só te, espaços?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Está em maiúsculas?', n.isupper())
print('Está em minúsculas?', n.islower())
print('Está capitalizada?', n.istitle())
print(n.isascii())
print(n.isdecimal())
print(n.isdigit())
print(n.isidentifier())
print(n.isprintable())